version: '3.6'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_PASSWORD="postgres"
    - POSTGRES_USER="postgres"
    
  backend:
    image: sing_for_needs:test
    ports:
      - "8080:8080"
    depends_on: 
      - db